/**
 * Order Forward Redux Constants
 * Action types for order forwarding and connection management
 */

// ============= CONNECTION MANAGEMENT =============
export const SEND_CONNECTION_REQUEST = 'SEND_CONNECTION_REQUEST';
export const SEND_CONNECTION_SUCCESS = 'SEND_CONNECTION_SUCCESS';
export const SEND_CONNECTION_FAILURE = 'SEND_CONNECTION_FAILURE';

export const RESPOND_TO_CONNECTION_REQUEST = 'RESPOND_TO_CONNECTION_REQUEST';
export const RESPOND_TO_CONNECTION_SUCCESS = 'RESPOND_TO_CONNECTION_SUCCESS';
export const RESPOND_TO_CONNECTION_FAILURE = 'RESPOND_TO_CONNECTION_FAILURE';

export const FETCH_CONNECTIONS_REQUEST = 'FETCH_CONNECTIONS_REQUEST';
export const FETCH_CONNECTIONS_SUCCESS = 'FETCH_CONNECTIONS_SUCCESS';
export const FETCH_CONNECTIONS_FAILURE = 'FETCH_CONNECTIONS_FAILURE';

export const FETCH_PENDING_REQUESTS_REQUEST = 'FETCH_PENDING_REQUESTS_REQUEST';
export const FETCH_PENDING_REQUESTS_SUCCESS = 'FETCH_PENDING_REQUESTS_SUCCESS';
export const FETCH_PENDING_REQUESTS_FAILURE = 'FETCH_PENDING_REQUESTS_FAILURE';

export const FETCH_SENT_REQUESTS_REQUEST = 'FETCH_SENT_REQUESTS_REQUEST';
export const FETCH_SENT_REQUESTS_SUCCESS = 'FETCH_SENT_REQUESTS_SUCCESS';
export const FETCH_SENT_REQUESTS_FAILURE = 'FETCH_SENT_REQUESTS_FAILURE';

export const REMOVE_CONNECTION_REQUEST = 'REMOVE_CONNECTION_REQUEST';
export const REMOVE_CONNECTION_SUCCESS = 'REMOVE_CONNECTION_SUCCESS';
export const REMOVE_CONNECTION_FAILURE = 'REMOVE_CONNECTION_FAILURE';

// ============= ORDER FORWARDING =============
export const FORWARD_ORDER_REQUEST = 'FORWARD_ORDER_REQUEST';
export const FORWARD_ORDER_SUCCESS = 'FORWARD_ORDER_SUCCESS';
export const FORWARD_ORDER_FAILURE = 'FORWARD_ORDER_FAILURE';

export const FETCH_RECEIVED_ORDERS_REQUEST = 'FETCH_RECEIVED_ORDERS_REQUEST';
export const FETCH_RECEIVED_ORDERS_SUCCESS = 'FETCH_RECEIVED_ORDERS_SUCCESS';
export const FETCH_RECEIVED_ORDERS_FAILURE = 'FETCH_RECEIVED_ORDERS_FAILURE';

export const FETCH_FORWARDED_ORDERS_REQUEST = 'FETCH_FORWARDED_ORDERS_REQUEST';
export const FETCH_FORWARDED_ORDERS_SUCCESS = 'FETCH_FORWARDED_ORDERS_SUCCESS';
export const FETCH_FORWARDED_ORDERS_FAILURE = 'FETCH_FORWARDED_ORDERS_FAILURE';

export const FETCH_FORWARDING_CHAIN_REQUEST = 'FETCH_FORWARDING_CHAIN_REQUEST';
export const FETCH_FORWARDING_CHAIN_SUCCESS = 'FETCH_FORWARDING_CHAIN_SUCCESS';
export const FETCH_FORWARDING_CHAIN_FAILURE = 'FETCH_FORWARDING_CHAIN_FAILURE';

// ============= ORDER ACCEPTANCE =============
export const FETCH_PENDING_ORDERS_REQUEST = 'FETCH_PENDING_ORDERS_REQUEST';
export const FETCH_PENDING_ORDERS_SUCCESS = 'FETCH_PENDING_ORDERS_SUCCESS';
export const FETCH_PENDING_ORDERS_FAILURE = 'FETCH_PENDING_ORDERS_FAILURE';

export const FETCH_ACCEPTED_ORDERS_REQUEST = 'FETCH_ACCEPTED_ORDERS_REQUEST';
export const FETCH_ACCEPTED_ORDERS_SUCCESS = 'FETCH_ACCEPTED_ORDERS_SUCCESS';
export const FETCH_ACCEPTED_ORDERS_FAILURE = 'FETCH_ACCEPTED_ORDERS_FAILURE';

export const FETCH_DENIED_ORDERS_REQUEST = 'FETCH_DENIED_ORDERS_REQUEST';
export const FETCH_DENIED_ORDERS_SUCCESS = 'FETCH_DENIED_ORDERS_SUCCESS';
export const FETCH_DENIED_ORDERS_FAILURE = 'FETCH_DENIED_ORDERS_FAILURE';

export const ACCEPT_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
export const ACCEPT_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAILURE = 'ACCEPT_ORDER_FAILURE';

export const DENY_ORDER_REQUEST = 'DENY_ORDER_REQUEST';
export const DENY_ORDER_SUCCESS = 'DENY_ORDER_SUCCESS';
export const DENY_ORDER_FAILURE = 'DENY_ORDER_FAILURE';

// ============= STATUS SYNC =============
export const SYNC_STATUS_REQUEST = 'SYNC_STATUS_REQUEST';
export const SYNC_STATUS_SUCCESS = 'SYNC_STATUS_SUCCESS';
export const SYNC_STATUS_FAILURE = 'SYNC_STATUS_FAILURE';

// ============= UI STATE =============
export const SET_FORWARD_MODAL_OPEN = 'SET_FORWARD_MODAL_OPEN';
export const SET_CONNECTION_MODAL_OPEN = 'SET_CONNECTION_MODAL_OPEN';
export const CLEAR_ORDER_FORWARD_ERROR = 'CLEAR_ORDER_FORWARD_ERROR';
export const CLEAR_ORDER_FORWARD_SUCCESS = 'CLEAR_ORDER_FORWARD_SUCCESS';
