// PrintingSpec Action Types
export const ADD_PRINTING_SPEC_REQUEST = "ADD_PRINTING_SPEC_REQUEST";
export const ADD_PRINTING_SPEC_SUCCESS = "ADD_PRINTING_SPEC_SUCCESS";
export const ADD_PRINTING_SPEC_FAIL = "ADD_PRINTING_SPEC_FAIL";

export const GET_PRINTING_SPECS_REQUEST = "GET_PRINTING_SPECS_REQUEST";
export const GET_PRINTING_SPECS_SUCCESS = "GET_PRINTING_SPECS_SUCCESS";
export const GET_PRINTING_SPECS_FAIL = "GET_PRINTING_SPECS_FAIL";

export const UPDATE_PRINTING_SPEC_REQUEST = "UPDATE_PRINTING_SPEC_REQUEST";
export const UPDATE_PRINTING_SPEC_SUCCESS = "UPDATE_PRINTING_SPEC_SUCCESS";
export const UPDATE_PRINTING_SPEC_FAIL = "UPDATE_PRINTING_SPEC_FAIL";

export const DELETE_PRINTING_SPEC_REQUEST = "DELETE_PRINTING_SPEC_REQUEST";
export const DELETE_PRINTING_SPEC_SUCCESS = "DELETE_PRINTING_SPEC_SUCCESS";
export const DELETE_PRINTING_SPEC_FAIL = "DELETE_PRINTING_SPEC_FAIL";
