// Order Type Create
export const CREATE_ORDER_TYPE_REQUEST = "CREATE_ORDER_TYPE_REQUEST";
export const CREATE_ORDER_TYPE_SUCCESS = "CREATE_ORDER_TYPE_SUCCESS";
export const CREATE_ORDER_TYPE_FAIL = "CREATE_ORDER_TYPE_FAIL";

// Order Type List
export const GET_ORDER_TYPES_REQUEST = "GET_ORDER_TYPES_REQUEST";
export const GET_ORDER_TYPES_SUCCESS = "GET_ORDER_TYPES_SUCCESS";
export const GET_ORDER_TYPES_FAIL = "GET_ORDER_TYPES_FAIL";

// Order Type Get by ID
export const GET_ORDER_TYPE_BY_ID_REQUEST = "GET_ORDER_TYPE_BY_ID_REQUEST";
export const GET_ORDER_TYPE_BY_ID_SUCCESS = "GET_ORDER_TYPE_BY_ID_SUCCESS";
export const GET_ORDER_TYPE_BY_ID_FAIL = "GET_ORDER_TYPE_BY_ID_FAIL";

// Order Type Get by Branch
export const GET_ORDER_TYPES_BY_BRANCH_REQUEST = "GET_ORDER_TYPES_BY_BRANCH_REQUEST";
export const GET_ORDER_TYPES_BY_BRANCH_SUCCESS = "GET_ORDER_TYPES_BY_BRANCH_SUCCESS";
export const GET_ORDER_TYPES_BY_BRANCH_FAIL = "GET_ORDER_TYPES_BY_BRANCH_FAIL";

// Order Type Get Default
export const GET_DEFAULT_ORDER_TYPE_REQUEST = "GET_DEFAULT_ORDER_TYPE_REQUEST";
export const GET_DEFAULT_ORDER_TYPE_SUCCESS = "GET_DEFAULT_ORDER_TYPE_SUCCESS";
export const GET_DEFAULT_ORDER_TYPE_FAIL = "GET_DEFAULT_ORDER_TYPE_FAIL";

// Order Type Update
export const UPDATE_ORDER_TYPE_REQUEST = "UPDATE_ORDER_TYPE_REQUEST";
export const UPDATE_ORDER_TYPE_SUCCESS = "UPDATE_ORDER_TYPE_SUCCESS";
export const UPDATE_ORDER_TYPE_FAIL = "UPDATE_ORDER_TYPE_FAIL";

// Order Type Delete
export const DELETE_ORDER_TYPE_REQUEST = "DELETE_ORDER_TYPE_REQUEST";
export const DELETE_ORDER_TYPE_SUCCESS = "DELETE_ORDER_TYPE_SUCCESS";
export const DELETE_ORDER_TYPE_FAIL = "DELETE_ORDER_TYPE_FAIL";

// Order Type Activate
export const ACTIVATE_ORDER_TYPE_REQUEST = "ACTIVATE_ORDER_TYPE_REQUEST";
export const ACTIVATE_ORDER_TYPE_SUCCESS = "ACTIVATE_ORDER_TYPE_SUCCESS";
export const ACTIVATE_ORDER_TYPE_FAIL = "ACTIVATE_ORDER_TYPE_FAIL";

// Order Type Deactivate
export const DEACTIVATE_ORDER_TYPE_REQUEST = "DEACTIVATE_ORDER_TYPE_REQUEST";
export const DEACTIVATE_ORDER_TYPE_SUCCESS = "DEACTIVATE_ORDER_TYPE_SUCCESS";
export const DEACTIVATE_ORDER_TYPE_FAIL = "DEACTIVATE_ORDER_TYPE_FAIL";

// Order Type Set Default
export const SET_DEFAULT_ORDER_TYPE_REQUEST = "SET_DEFAULT_ORDER_TYPE_REQUEST";
export const SET_DEFAULT_ORDER_TYPE_SUCCESS = "SET_DEFAULT_ORDER_TYPE_SUCCESS";
export const SET_DEFAULT_ORDER_TYPE_FAIL = "SET_DEFAULT_ORDER_TYPE_FAIL";
