// Machine Table Action Types
export const FETCH_MACHINE_TABLE_REQUEST = 'FETCH_MACHINE_TABLE_REQUEST';
export const FETCH_MACHINE_TABLE_SUCCESS = 'FETCH_MACHINE_TABLE_SUCCESS';
export const FETCH_MACHINE_TABLE_FAILURE = 'FETCH_MACHINE_TABLE_FAILURE';

export const CLEAR_MACHINE_TABLE_DATA = 'CLEAR_MACHINE_TABLE_DATA';
export const CLEAR_MACHINE_TABLE_ERROR = 'CLEAR_MACHINE_TABLE_ERROR';

export const SET_SELECTED_MACHINE = 'SET_SELECTED_MACHINE';
export const CLEAR_SELECTED_MACHINE = 'CLEAR_SELECTED_MACHINE';

export const UPDATE_TABLE_ROW_REQUEST = 'UPDATE_TABLE_ROW_REQUEST';
export const UPDATE_TABLE_ROW_SUCCESS = 'UPDATE_TABLE_ROW_SUCCESS';
export const UPDATE_TABLE_ROW_FAILURE = 'UPDATE_TABLE_ROW_FAILURE';

export const DELETE_TABLE_ROW_REQUEST = 'DELETE_TABLE_ROW_REQUEST';
export const DELETE_TABLE_ROW_SUCCESS = 'DELETE_TABLE_ROW_SUCCESS';
export const DELETE_TABLE_ROW_FAILURE = 'DELETE_TABLE_ROW_FAILURE';

export const ADD_TABLE_ROW_REQUEST = 'ADD_TABLE_ROW_REQUEST';
export const ADD_TABLE_ROW_SUCCESS = 'ADD_TABLE_ROW_SUCCESS';
export const ADD_TABLE_ROW_FAILURE = 'ADD_TABLE_ROW_FAILURE';

// Machine Configuration
export const FETCH_MACHINE_CONFIG_REQUEST = 'FETCH_MACHINE_CONFIG_REQUEST';
export const FETCH_MACHINE_CONFIG_SUCCESS = 'FETCH_MACHINE_CONFIG_SUCCESS';
export const FETCH_MACHINE_CONFIG_FAILURE = 'FETCH_MACHINE_CONFIG_FAILURE';

// Save/Update Machine Table Config (View Template)
export const SAVE_MACHINE_CONFIG_REQUEST = 'SAVE_MACHINE_CONFIG_REQUEST';
export const SAVE_MACHINE_CONFIG_SUCCESS = 'SAVE_MACHINE_CONFIG_SUCCESS';
export const SAVE_MACHINE_CONFIG_FAILURE = 'SAVE_MACHINE_CONFIG_FAILURE';

export const UPDATE_MACHINE_CONFIG_REQUEST = 'UPDATE_MACHINE_CONFIG_REQUEST';
export const UPDATE_MACHINE_CONFIG_SUCCESS = 'UPDATE_MACHINE_CONFIG_SUCCESS';
export const UPDATE_MACHINE_CONFIG_FAILURE = 'UPDATE_MACHINE_CONFIG_FAILURE';