// Get Orders for Machine
export const GET_MACHINE_ORDERS_REQUEST = "GET_MACHINE_ORDERS_REQUEST";
export const GET_MACHINE_ORDERS_SUCCESS = "GET_MACHINE_ORDERS_SUCCESS";
export const GET_MACHINE_ORDERS_FAIL = "GET_MACHINE_ORDERS_FAIL";

// Get Order Table Data
export const GET_ORDER_TABLE_DATA_REQUEST = "GET_ORDER_TABLE_DATA_REQUEST";
export const GET_ORDER_TABLE_DATA_SUCCESS = "GET_ORDER_TABLE_DATA_SUCCESS";
export const GET_ORDER_TABLE_DATA_FAIL = "GET_ORDER_TABLE_DATA_FAIL";

// Add Table Row
export const ADD_TABLE_ROW_REQUEST = "ADD_TABLE_ROW_REQUEST";
export const ADD_TABLE_ROW_SUCCESS = "ADD_TABLE_ROW_SUCCESS";
export const ADD_TABLE_ROW_FAIL = "ADD_TABLE_ROW_FAIL";

// Update Table Row
export const UPDATE_TABLE_ROW_REQUEST = "UPDATE_TABLE_ROW_REQUEST";
export const UPDATE_TABLE_ROW_SUCCESS = "UPDATE_TABLE_ROW_SUCCESS";
export const UPDATE_TABLE_ROW_FAIL = "UPDATE_TABLE_ROW_FAIL";

// Delete Table Row
export const DELETE_TABLE_ROW_REQUEST = "DELETE_TABLE_ROW_REQUEST";
export const DELETE_TABLE_ROW_SUCCESS = "DELETE_TABLE_ROW_SUCCESS";
export const DELETE_TABLE_ROW_FAIL = "DELETE_TABLE_ROW_FAIL";

// Mark Order Complete
export const MARK_ORDER_COMPLETE_REQUEST = "MARK_ORDER_COMPLETE_REQUEST";
export const MARK_ORDER_COMPLETE_SUCCESS = "MARK_ORDER_COMPLETE_SUCCESS";
export const MARK_ORDER_COMPLETE_FAIL = "MARK_ORDER_COMPLETE_FAIL";

// WebSocket Events
export const WS_MACHINE_TABLE_ROW_ADDED = "WS_MACHINE_TABLE_ROW_ADDED";
export const WS_MACHINE_TABLE_ROW_UPDATED = "WS_MACHINE_TABLE_ROW_UPDATED";
export const WS_MACHINE_TABLE_ROW_DELETED = "WS_MACHINE_TABLE_ROW_DELETED";
export const WS_MACHINE_TABLE_ORDER_COMPLETE = "WS_MACHINE_TABLE_ORDER_COMPLETE";

// Clear State
export const CLEAR_OPERATOR_VIEW_ERROR = "CLEAR_OPERATOR_VIEW_ERROR";
export const CLEAR_ORDER_TABLE_DATA = "CLEAR_ORDER_TABLE_DATA";
export const SET_SELECTED_ORDER = "SET_SELECTED_ORDER";
