// Print Type Create
export const CREATE_PRINT_TYPE_REQUEST = "CREATE_PRINT_TYPE_REQUEST";
export const CREATE_PRINT_TYPE_SUCCESS = "CREATE_PRINT_TYPE_SUCCESS";
export const CREATE_PRINT_TYPE_FAIL = "CREATE_PRINT_TYPE_FAIL";

// Print Type List
export const GET_PRINT_TYPES_REQUEST = "GET_PRINT_TYPES_REQUEST";
export const GET_PRINT_TYPES_SUCCESS = "GET_PRINT_TYPES_SUCCESS";
export const GET_PRINT_TYPES_FAIL = "GET_PRINT_TYPES_FAIL";

// Print Type Get by ID
export const GET_PRINT_TYPE_BY_ID_REQUEST = "GET_PRINT_TYPE_BY_ID_REQUEST";
export const GET_PRINT_TYPE_BY_ID_SUCCESS = "GET_PRINT_TYPE_BY_ID_SUCCESS";
export const GET_PRINT_TYPE_BY_ID_FAIL = "GET_PRINT_TYPE_BY_ID_FAIL";

// Print Type Get by Branch
export const GET_PRINT_TYPES_BY_BRANCH_REQUEST = "GET_PRINT_TYPES_BY_BRANCH_REQUEST";
export const GET_PRINT_TYPES_BY_BRANCH_SUCCESS = "GET_PRINT_TYPES_BY_BRANCH_SUCCESS";
export const GET_PRINT_TYPES_BY_BRANCH_FAIL = "GET_PRINT_TYPES_BY_BRANCH_FAIL";

// Print Type Get by Order Type
export const GET_PRINT_TYPES_BY_ORDER_TYPE_REQUEST = "GET_PRINT_TYPES_BY_ORDER_TYPE_REQUEST";
export const GET_PRINT_TYPES_BY_ORDER_TYPE_SUCCESS = "GET_PRINT_TYPES_BY_ORDER_TYPE_SUCCESS";
export const GET_PRINT_TYPES_BY_ORDER_TYPE_FAIL = "GET_PRINT_TYPES_BY_ORDER_TYPE_FAIL";

// Print Type Get Default
export const GET_DEFAULT_PRINT_TYPE_REQUEST = "GET_DEFAULT_PRINT_TYPE_REQUEST";
export const GET_DEFAULT_PRINT_TYPE_SUCCESS = "GET_DEFAULT_PRINT_TYPE_SUCCESS";
export const GET_DEFAULT_PRINT_TYPE_FAIL = "GET_DEFAULT_PRINT_TYPE_FAIL";

// Print Type Update
export const UPDATE_PRINT_TYPE_REQUEST = "UPDATE_PRINT_TYPE_REQUEST";
export const UPDATE_PRINT_TYPE_SUCCESS = "UPDATE_PRINT_TYPE_SUCCESS";
export const UPDATE_PRINT_TYPE_FAIL = "UPDATE_PRINT_TYPE_FAIL";

// Print Type Delete
export const DELETE_PRINT_TYPE_REQUEST = "DELETE_PRINT_TYPE_REQUEST";
export const DELETE_PRINT_TYPE_SUCCESS = "DELETE_PRINT_TYPE_SUCCESS";
export const DELETE_PRINT_TYPE_FAIL = "DELETE_PRINT_TYPE_FAIL";

// Print Type Activate
export const ACTIVATE_PRINT_TYPE_REQUEST = "ACTIVATE_PRINT_TYPE_REQUEST";
export const ACTIVATE_PRINT_TYPE_SUCCESS = "ACTIVATE_PRINT_TYPE_SUCCESS";
export const ACTIVATE_PRINT_TYPE_FAIL = "ACTIVATE_PRINT_TYPE_FAIL";

// Print Type Deactivate
export const DEACTIVATE_PRINT_TYPE_REQUEST = "DEACTIVATE_PRINT_TYPE_REQUEST";
export const DEACTIVATE_PRINT_TYPE_SUCCESS = "DEACTIVATE_PRINT_TYPE_SUCCESS";
export const DEACTIVATE_PRINT_TYPE_FAIL = "DEACTIVATE_PRINT_TYPE_FAIL";

// Print Type Set Default
export const SET_DEFAULT_PRINT_TYPE_REQUEST = "SET_DEFAULT_PRINT_TYPE_REQUEST";
export const SET_DEFAULT_PRINT_TYPE_SUCCESS = "SET_DEFAULT_PRINT_TYPE_SUCCESS";
export const SET_DEFAULT_PRINT_TYPE_FAIL = "SET_DEFAULT_PRINT_TYPE_FAIL";
