// Material Spec Create
export const CREATE_MATERIAL_SPEC_REQUEST = "CREATE_MATERIAL_SPEC_REQUEST";
export const CREATE_MATERIAL_SPEC_SUCCESS = "CREATE_MATERIAL_SPEC_SUCCESS";
export const CREATE_MATERIAL_SPEC_FAIL = "CREATE_MATERIAL_SPEC_FAIL";

// Material Spec List
export const GET_MATERIAL_SPECS_REQUEST = "GET_MATERIAL_SPECS_REQUEST";
export const GET_MATERIAL_SPECS_SUCCESS = "GET_MATERIAL_SPECS_SUCCESS";
export const GET_MATERIAL_SPECS_FAIL = "GET_MATERIAL_SPECS_FAIL";

// Material Spec Get by ID
export const GET_MATERIAL_SPEC_BY_ID_REQUEST = "GET_MATERIAL_SPEC_BY_ID_REQUEST";
export const GET_MATERIAL_SPEC_BY_ID_SUCCESS = "GET_MATERIAL_SPEC_BY_ID_SUCCESS";
export const GET_MATERIAL_SPEC_BY_ID_FAIL = "GET_MATERIAL_SPEC_BY_ID_FAIL";

// Material Spec Get by Material Type
export const GET_MATERIAL_SPECS_BY_TYPE_REQUEST = "GET_MATERIAL_SPECS_BY_TYPE_REQUEST";
export const GET_MATERIAL_SPECS_BY_TYPE_SUCCESS = "GET_MATERIAL_SPECS_BY_TYPE_SUCCESS";
export const GET_MATERIAL_SPECS_BY_TYPE_FAIL = "GET_MATERIAL_SPECS_BY_TYPE_FAIL";

// Material Spec Update
export const UPDATE_MATERIAL_SPEC_REQUEST = "UPDATE_MATERIAL_SPEC_REQUEST";
export const UPDATE_MATERIAL_SPEC_SUCCESS = "UPDATE_MATERIAL_SPEC_SUCCESS";
export const UPDATE_MATERIAL_SPEC_FAIL = "UPDATE_MATERIAL_SPEC_FAIL";

// Material Spec Delete
export const DELETE_MATERIAL_SPEC_REQUEST = "DELETE_MATERIAL_SPEC_REQUEST";
export const DELETE_MATERIAL_SPEC_SUCCESS = "DELETE_MATERIAL_SPEC_SUCCESS";
export const DELETE_MATERIAL_SPEC_FAIL = "DELETE_MATERIAL_SPEC_FAIL";

// Material Spec Activate
export const ACTIVATE_MATERIAL_SPEC_REQUEST = "ACTIVATE_MATERIAL_SPEC_REQUEST";
export const ACTIVATE_MATERIAL_SPEC_SUCCESS = "ACTIVATE_MATERIAL_SPEC_SUCCESS";
export const ACTIVATE_MATERIAL_SPEC_FAIL = "ACTIVATE_MATERIAL_SPEC_FAIL";

// Material Spec Deactivate
export const DEACTIVATE_MATERIAL_SPEC_REQUEST = "DEACTIVATE_MATERIAL_SPEC_REQUEST";
export const DEACTIVATE_MATERIAL_SPEC_SUCCESS = "DEACTIVATE_MATERIAL_SPEC_SUCCESS";
export const DEACTIVATE_MATERIAL_SPEC_FAIL = "DEACTIVATE_MATERIAL_SPEC_FAIL";
