// Excel Export Type Create
export const CREATE_EXCEL_EXPORT_TYPE_REQUEST = "CREATE_EXCEL_EXPORT_TYPE_REQUEST";
export const CREATE_EXCEL_EXPORT_TYPE_SUCCESS = "CREATE_EXCEL_EXPORT_TYPE_SUCCESS";
export const CREATE_EXCEL_EXPORT_TYPE_FAIL = "CREATE_EXCEL_EXPORT_TYPE_FAIL";

// Excel Export Type List
export const GET_EXCEL_EXPORT_TYPES_REQUEST = "GET_EXCEL_EXPORT_TYPES_REQUEST";
export const GET_EXCEL_EXPORT_TYPES_SUCCESS = "GET_EXCEL_EXPORT_TYPES_SUCCESS";
export const GET_EXCEL_EXPORT_TYPES_FAIL = "GET_EXCEL_EXPORT_TYPES_FAIL";

// Excel Export Type Get by ID
export const GET_EXCEL_EXPORT_TYPE_BY_ID_REQUEST = "GET_EXCEL_EXPORT_TYPE_BY_ID_REQUEST";
export const GET_EXCEL_EXPORT_TYPE_BY_ID_SUCCESS = "GET_EXCEL_EXPORT_TYPE_BY_ID_SUCCESS";
export const GET_EXCEL_EXPORT_TYPE_BY_ID_FAIL = "GET_EXCEL_EXPORT_TYPE_BY_ID_FAIL";

// Excel Export Type Get by Branch
export const GET_EXCEL_EXPORT_TYPES_BY_BRANCH_REQUEST = "GET_EXCEL_EXPORT_TYPES_BY_BRANCH_REQUEST";
export const GET_EXCEL_EXPORT_TYPES_BY_BRANCH_SUCCESS = "GET_EXCEL_EXPORT_TYPES_BY_BRANCH_SUCCESS";
export const GET_EXCEL_EXPORT_TYPES_BY_BRANCH_FAIL = "GET_EXCEL_EXPORT_TYPES_BY_BRANCH_FAIL";

// Excel Export Type Get by Option Type
export const GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_REQUEST = "GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_REQUEST";
export const GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_SUCCESS = "GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_SUCCESS";
export const GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_FAIL = "GET_EXCEL_EXPORT_TYPES_BY_OPTION_TYPE_FAIL";

// Excel Export Type Get Default
export const GET_DEFAULT_EXCEL_EXPORT_TYPE_REQUEST = "GET_DEFAULT_EXCEL_EXPORT_TYPE_REQUEST";
export const GET_DEFAULT_EXCEL_EXPORT_TYPE_SUCCESS = "GET_DEFAULT_EXCEL_EXPORT_TYPE_SUCCESS";
export const GET_DEFAULT_EXCEL_EXPORT_TYPE_FAIL = "GET_DEFAULT_EXCEL_EXPORT_TYPE_FAIL";

// Excel Export Type Update
export const UPDATE_EXCEL_EXPORT_TYPE_REQUEST = "UPDATE_EXCEL_EXPORT_TYPE_REQUEST";
export const UPDATE_EXCEL_EXPORT_TYPE_SUCCESS = "UPDATE_EXCEL_EXPORT_TYPE_SUCCESS";
export const UPDATE_EXCEL_EXPORT_TYPE_FAIL = "UPDATE_EXCEL_EXPORT_TYPE_FAIL";

// Excel Export Type Delete
export const DELETE_EXCEL_EXPORT_TYPE_REQUEST = "DELETE_EXCEL_EXPORT_TYPE_REQUEST";
export const DELETE_EXCEL_EXPORT_TYPE_SUCCESS = "DELETE_EXCEL_EXPORT_TYPE_SUCCESS";
export const DELETE_EXCEL_EXPORT_TYPE_FAIL = "DELETE_EXCEL_EXPORT_TYPE_FAIL";

// Excel Export Type Set Default
export const SET_DEFAULT_EXCEL_EXPORT_TYPE_REQUEST = "SET_DEFAULT_EXCEL_EXPORT_TYPE_REQUEST";
export const SET_DEFAULT_EXCEL_EXPORT_TYPE_SUCCESS = "SET_DEFAULT_EXCEL_EXPORT_TYPE_SUCCESS";
export const SET_DEFAULT_EXCEL_EXPORT_TYPE_FAIL = "SET_DEFAULT_EXCEL_EXPORT_TYPE_FAIL";
