export const DEVICE_ACCESS_CREATE_REQUEST = "DEVICE_ACCESS_CREATE_REQUEST";
export const DEVICE_ACCESS_CREATE_SUCCESS = "DEVICE_ACCESS_CREATE_SUCCESS";
export const DEVICE_ACCESS_CREATE_FAIL = "DEVICE_ACCESS_CREATE_FAIL";

export const DEVICE_ACCESS_LIST_REQUEST = "DEVICE_ACCESS_LIST_REQUEST";
export const DEVICE_ACCESS_LIST_SUCCESS = "DEVICE_ACCESS_LIST_SUCCESS";
export const DEVICE_ACCESS_LIST_FAIL = "DEVICE_ACCESS_LIST_FAIL";

export const DEVICE_ACCESS_UPDATE_REQUEST = "DEVICE_ACCESS_UPDATE_REQUEST";
export const DEVICE_ACCESS_UPDATE_SUCCESS = "DEVICE_ACCESS_UPDATE_SUCCESS";
export const DEVICE_ACCESS_UPDATE_FAIL = "DEVICE_ACCESS_UPDATE_FAIL";

export const DEVICE_ACCESS_DELETE_REQUEST = "DEVICE_ACCESS_DELETE_REQUEST";
export const DEVICE_ACCESS_DELETE_SUCCESS = "DEVICE_ACCESS_DELETE_SUCCESS";
export const DEVICE_ACCESS_DELETE_FAIL = "DEVICE_ACCESS_DELETE_FAIL";