// Create
export const CREATE_CUSTOMER_PARENT_COMPANY_REQUEST = "CREATE_CUSTOMER_PARENT_COMPANY_REQUEST";
export const CREATE_CUSTOMER_PARENT_COMPANY_SUCCESS = "CREATE_CUSTOMER_PARENT_COMPANY_SUCCESS";
export const CREATE_CUSTOMER_PARENT_COMPANY_FAIL = "CREATE_CUSTOMER_PARENT_COMPANY_FAIL";

// Read (Get)
export const GET_CUSTOMER_PARENT_COMPANIES_REQUEST = "GET_CUSTOMER_PARENT_COMPANIES_REQUEST";
export const GET_CUSTOMER_PARENT_COMPANIES_SUCCESS = "GET_CUSTOMER_PARENT_COMPANIES_SUCCESS";
export const GET_CUSTOMER_PARENT_COMPANIES_FAIL = "GET_CUSTOMER_PARENT_COMPANIES_FAIL";

// Update
export const UPDATE_CUSTOMER_PARENT_COMPANY_REQUEST = "UPDATE_CUSTOMER_PARENT_COMPANY_REQUEST";
export const UPDATE_CUSTOMER_PARENT_COMPANY_SUCCESS = "UPDATE_CUSTOMER_PARENT_COMPANY_SUCCESS";
export const UPDATE_CUSTOMER_PARENT_COMPANY_FAIL = "UPDATE_CUSTOMER_PARENT_COMPANY_FAIL";

// Delete
export const DELETE_CUSTOMER_PARENT_COMPANY_REQUEST = "DELETE_CUSTOMER_PARENT_COMPANY_REQUEST";
export const DELETE_CUSTOMER_PARENT_COMPANY_SUCCESS = "DELETE_CUSTOMER_PARENT_COMPANY_SUCCESS";
export const DELETE_CUSTOMER_PARENT_COMPANY_FAIL = "DELETE_CUSTOMER_PARENT_COMPANY_FAIL";
