// OdersContants.ts - Order Action Constants

// Order CRUD Operations
export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST';
export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS';
export const ORDER_SAVE_FAILURE = 'ORDER_SAVE_FAILURE';
export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAILURE = 'ORDER_UPDATE_FAILURE';
export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE';
export const ORDER_FETCH_REQUEST = 'ORDER_FETCH_REQUEST';
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILURE = 'ORDER_FETCH_FAILURE';

// Order State Management
export const ORDER_RESET = 'ORDER_RESET';
export const ORDER_CLEAR = 'ORDER_CLEAR';

// Form Data Management
export const COLLECT_FORM_DATA = 'COLLECT_FORM_DATA';
export const VALIDATE_FORM_DATA = 'VALIDATE_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';

// UI State Management
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';
export const SET_WARNING_MESSAGE = 'SET_WARNING_MESSAGE';
export const CLEAR_WARNING_MESSAGE = 'CLEAR_WARNING_MESSAGE';

// Order List Management
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const SET_ORDERS_FILTER = 'SET_ORDERS_FILTER';
export const CLEAR_ORDERS_FILTER = 'CLEAR_ORDERS_FILTER';

// Order Status Updates
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_MACHINE_STATUS = 'UPDATE_MACHINE_STATUS';
export const ASSIGN_OPERATOR = 'ASSIGN_OPERATOR';
export const UPDATE_STEP_STATUS = 'UPDATE_STEP_STATUS';

// Machine and Step Management
export const ADD_MACHINE_TO_STEP = 'ADD_MACHINE_TO_STEP';
export const REMOVE_MACHINE_FROM_STEP = 'REMOVE_MACHINE_FROM_STEP';
export const UPDATE_MACHINE_IN_STEP = 'UPDATE_MACHINE_IN_STEP';
export const ADD_STEP_TO_ORDER = 'ADD_STEP_TO_ORDER';
export const REMOVE_STEP_FROM_ORDER = 'REMOVE_STEP_FROM_ORDER';
export const UPDATE_STEP_IN_ORDER = 'UPDATE_STEP_IN_ORDER';




// Account Orders Management
export const GET_ACCOUNT_ORDERS_REQUEST = 'GET_ACCOUNT_ORDERS_REQUEST';
export const GET_ACCOUNT_ORDERS_SUCCESS = 'GET_ACCOUNT_ORDERS_SUCCESS';
export const GET_ACCOUNT_ORDERS_FAILURE = 'GET_ACCOUNT_ORDERS_FAILURE';


