// orderConstants.ts - Order Action Constants

// Order CRUD Operations
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ORDER_BY_ID_REQUEST = 'FETCH_ORDER_BY_ID_REQUEST';
export const FETCH_ORDER_BY_ID_SUCCESS = 'FETCH_ORDER_BY_ID_SUCCESS';
export const FETCH_ORDER_BY_ID_FAILURE = 'FETCH_ORDER_BY_ID_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

// Order Status Management
export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

// Machine Operations
export const COMPLETE_MACHINE_REQUEST = 'COMPLETE_MACHINE_REQUEST';
export const COMPLETE_MACHINE_SUCCESS = 'COMPLETE_MACHINE_SUCCESS';
export const COMPLETE_MACHINE_FAILURE = 'COMPLETE_MACHINE_FAILURE';

export const UPDATE_MACHINE_STATUS_REQUEST = 'UPDATE_MACHINE_STATUS_REQUEST';
export const UPDATE_MACHINE_STATUS_SUCCESS = 'UPDATE_MACHINE_STATUS_SUCCESS';
export const UPDATE_MACHINE_STATUS_FAILURE = 'UPDATE_MACHINE_STATUS_FAILURE';

// Step Operations
export const PROGRESS_TO_NEXT_STEP_REQUEST = 'PROGRESS_TO_NEXT_STEP_REQUEST';
export const PROGRESS_TO_NEXT_STEP_SUCCESS = 'PROGRESS_TO_NEXT_STEP_SUCCESS';
export const PROGRESS_TO_NEXT_STEP_FAILURE = 'PROGRESS_TO_NEXT_STEP_FAILURE';

export const UPDATE_STEP_STATUS_REQUEST = 'UPDATE_STEP_STATUS_REQUEST';
export const UPDATE_STEP_STATUS_SUCCESS = 'UPDATE_STEP_STATUS_SUCCESS';
export const UPDATE_STEP_STATUS_FAILURE = 'UPDATE_STEP_STATUS_FAILURE';

// Real-time Data
export const UPDATE_REALTIME_DATA_REQUEST = 'UPDATE_REALTIME_DATA_REQUEST';
export const UPDATE_REALTIME_DATA_SUCCESS = 'UPDATE_REALTIME_DATA_SUCCESS';
export const UPDATE_REALTIME_DATA_FAILURE = 'UPDATE_REALTIME_DATA_FAILURE';

// Notes
export const ADD_ORDER_NOTE_REQUEST = 'ADD_ORDER_NOTE_REQUEST';
export const ADD_ORDER_NOTE_SUCCESS = 'ADD_ORDER_NOTE_SUCCESS';
export const ADD_ORDER_NOTE_FAILURE = 'ADD_ORDER_NOTE_FAILURE';

// Quality Control
export const UPDATE_QUALITY_CONTROL_REQUEST = 'UPDATE_QUALITY_CONTROL_REQUEST';
export const UPDATE_QUALITY_CONTROL_SUCCESS = 'UPDATE_QUALITY_CONTROL_SUCCESS';
export const UPDATE_QUALITY_CONTROL_FAILURE = 'UPDATE_QUALITY_CONTROL_FAILURE';

// Dashboard and Reports
export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

export const FETCH_EFFICIENCY_REPORT_REQUEST = 'FETCH_EFFICIENCY_REPORT_REQUEST';
export const FETCH_EFFICIENCY_REPORT_SUCCESS = 'FETCH_EFFICIENCY_REPORT_SUCCESS';
export const FETCH_EFFICIENCY_REPORT_FAILURE = 'FETCH_EFFICIENCY_REPORT_FAILURE';

// Filters and State Management
export const SET_ORDER_FILTERS = 'SET_ORDER_FILTERS';
export const CLEAR_ORDER_FILTERS = 'CLEAR_ORDER_FILTERS';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const CLEAR_CURRENT_ORDER = 'CLEAR_CURRENT_ORDER';

// UI State
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';
