import React from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// STYLES
// ─────────────────────────────────────────────────────────────────────────────

export const S: Record<string, React.CSSProperties> = {
  overlay:         { position: 'fixed', inset: 0, background: 'rgba(15,17,23,0.65)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999 },
  modal:           { background: '#fff', borderRadius: 16, padding: '36px 32px 28px', width: '100%', maxWidth: 460, boxShadow: '0 24px 64px rgba(0,0,0,0.22)' },
  modalTitle:      { fontSize: 20, fontWeight: 800, color: '#0f172a', textAlign: 'center', marginTop: 8, marginBottom: 4 },
  modalSub:        { fontSize: 13, color: '#64748b', textAlign: 'center', marginBottom: 24 },
  presetRow:       { display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' },
  presetBtn:       { flex: 1, minWidth: 90, padding: '7px 10px', background: '#f1f5f9', border: '1.5px solid #e2e8f0', borderRadius: 8, fontSize: 12, fontWeight: 600, color: '#475569', cursor: 'pointer' },
  presetActive:    { background: '#eff6ff', borderColor: '#3b82f6', color: '#1d4ed8' },
  dateRow:         { display: 'flex', gap: 14, alignItems: 'flex-end', marginBottom: 16 },
  dateField:       { flex: 1, display: 'flex', flexDirection: 'column', gap: 6 },
  dateLabel:       { fontSize: 11, fontWeight: 700, color: '#374151', textTransform: 'uppercase', letterSpacing: '0.6px' },
  dateInput:       { padding: '9px 11px', border: '1.5px solid #d1d5db', borderRadius: 8, fontSize: 13, color: '#0f172a', outline: 'none', width: '100%' },
  cacheHint:       { background: '#fefce8', border: '1px solid #fde68a', borderRadius: 8, padding: '8px 12px', fontSize: 12, color: '#a16207', fontWeight: 600, marginBottom: 12, textAlign: 'center' },
  confirmBtn:      { width: '100%', padding: '12px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  bigSpinner:      { width: 52, height: 52, border: '4px solid #e2e8f0', borderTopColor: '#3b82f6', borderRadius: '50%', animation: 'spin .8s linear infinite', margin: '0 auto' },
  listPage:        { minHeight: '100vh', background: '#f8fafc', display: 'flex', flexDirection: 'column' },
  listHeader:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 24px', background: '#fff', borderBottom: '1px solid #e2e8f0', boxShadow: '0 1px 4px rgba(0,0,0,.05)', flexWrap: 'wrap', gap: 10 },
  listHeaderLeft:  { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  listTitle:       { fontSize: 18, fontWeight: 800, color: '#0f172a' },
  dateBadge:       { background: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: 20, padding: '4px 13px', fontSize: 12, fontWeight: 600, color: '#1d4ed8', whiteSpace: 'nowrap' },
  countBadge:      { background: '#f1f5f9', borderRadius: 20, padding: '4px 13px', fontSize: 12, fontWeight: 600, color: '#64748b' },
  cacheBadge:      { background: '#fefce8', border: '1px solid #fde68a', borderRadius: 20, padding: '4px 13px', fontSize: 12, fontWeight: 600, color: '#a16207', whiteSpace: 'nowrap' },
  secondaryBtn:    { padding: '7px 16px', background: '#f1f5f9', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 13, fontWeight: 600, color: '#374151', cursor: 'pointer' },
  searchBarWrap:   { padding: '10px 24px', background: '#fff', borderBottom: '1px solid #f1f5f9' },
  searchBar:       { display: 'flex', alignItems: 'center', gap: 10, maxWidth: 360, background: '#f8fafc', border: '1.5px solid #e2e8f0', borderRadius: 9, padding: '7px 13px' },
  searchInput:     { flex: 1, border: 'none', outline: 'none', fontSize: 14, color: '#0f172a', background: 'transparent', minWidth: 0 },
  clearBtn:        { background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 14 },
  grid:            { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16, padding: 24 },
  card:            { background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: 12, padding: '18px 20px', cursor: 'pointer', transition: 'transform .15s, box-shadow .15s, border-color .15s', display: 'flex', flexDirection: 'column', gap: 8, boxShadow: '0 1px 4px rgba(0,0,0,.06)' },
  cardTopRow:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  cardName:        { fontSize: 16, fontWeight: 700, color: '#0f172a', lineHeight: 1.3 },
  cardCode:        { fontSize: 11, color: '#94a3b8', fontFamily: 'monospace', fontWeight: 600 },
  cardDesc:        { fontSize: 12, color: '#64748b', lineHeight: 1.5, flexGrow: 1 },
  cardFooter:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 4, paddingTop: 10, borderTop: '1px solid #f1f5f9' },
  cardParts:       { fontSize: 11, color: '#94a3b8', fontFamily: 'monospace' },
  openBtn:         { fontSize: 12, fontWeight: 700, color: '#3b82f6' },
  catBadge:        { display: 'flex', alignItems: 'center', gap: 5, padding: '3px 9px', borderRadius: 20, fontSize: 11, fontWeight: 700, textTransform: 'capitalize' },
  catDot:          { width: 6, height: 6, borderRadius: '50%', flexShrink: 0 },
  tplBadge:        { padding: '3px 9px', borderRadius: 20, fontSize: 11, fontWeight: 600 },
  previewWrap:     { position: 'fixed', inset: 0, background: '#0f172a', display: 'flex', flexDirection: 'column', zIndex: 1000 },
  previewFull:     { zIndex: 9999 },
  previewBar:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 18px', background: '#1e293b', borderBottom: '1px solid #334155', flexWrap: 'wrap', gap: 8, flexShrink: 0 },
  previewBarLeft:  { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  previewBarRight: { display: 'flex', alignItems: 'center', gap: 8 },
  backBtn:         { padding: '6px 14px', background: '#334155', border: 'none', borderRadius: 7, color: '#94a3b8', fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  previewName:     { fontWeight: 700, fontSize: 15, color: '#f1f5f9' },
  previewCode:     { color: '#475569', fontFamily: 'monospace', fontSize: 13 },
  toolBtn:         { padding: '6px 13px', background: '#334155', border: '1px solid #475569', borderRadius: 7, color: '#cbd5e1', fontSize: 12, fontWeight: 600, cursor: 'pointer' },
  previewBody:     { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  iframe:          { flex: 1, width: '100%', border: 'none', background: '#fff' },
  stateBox:        { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 14, padding: 48, color: '#64748b', fontSize: 14, minHeight: 300 },
  spinner:         { width: 36, height: 36, border: '3px solid #e2e8f0', borderTopColor: '#3b82f6', borderRadius: '50%', animation: 'spin .7s linear infinite' },
  menuItem:        { display: 'flex', alignItems: 'center', gap: 12, width: '100%', padding: '10px 14px', background: 'none', border: 'none', cursor: 'pointer', textAlign: 'left', transition: 'background .1s' },
  menuIcon:        { fontSize: 20, width: 28, textAlign: 'center', flexShrink: 0 },
};
