export const ADD_MATERIAL_CATEGORY_REQUEST = "ADD_MATERIAL_CATEGORY_REQUEST";
export const ADD_MATERIAL_CATEGORY_SUCCESS = "ADD_MATERIAL_CATEGORY_SUCCESS";
export const ADD_MATERIAL_CATEGORY_FAIL = "ADD_MATERIAL_CATEGORY_FAIL";

export const GET_MATERIAL_CATEGORIES_REQUEST = "GET_MATERIAL_CATEGORIES_REQUEST";
export const GET_MATERIAL_CATEGORIES_SUCCESS = "GET_MATERIAL_CATEGORIES_SUCCESS";
export const GET_MATERIAL_CATEGORIES_FAIL = "GET_MATERIAL_CATEGORIES_FAIL";

export const GET_ALL_MATERIAL_TYPES_REQUEST = "GET_ALL_MATERIAL_TYPES_REQUEST";
export const GET_ALL_MATERIAL_TYPES_SUCCESS = "GET_ALL_MATERIAL_TYPES_SUCCESS";
export const GET_ALL_MATERIAL_TYPES_FAIL = "GET_ALL_MATERIAL_TYPES_FAIL";