// reportConstants.ts - Report Action Constants

// Overview Report
export const FETCH_OVERVIEW_REQUEST = 'FETCH_OVERVIEW_REQUEST';
export const FETCH_OVERVIEW_SUCCESS = 'FETCH_OVERVIEW_SUCCESS';
export const FETCH_OVERVIEW_FAILURE = 'FETCH_OVERVIEW_FAILURE';

// Orders Report
export const FETCH_ORDERS_REPORT_REQUEST = 'FETCH_ORDERS_REPORT_REQUEST';
export const FETCH_ORDERS_REPORT_SUCCESS = 'FETCH_ORDERS_REPORT_SUCCESS';
export const FETCH_ORDERS_REPORT_FAILURE = 'FETCH_ORDERS_REPORT_FAILURE';

// Production Report
export const FETCH_PRODUCTION_REQUEST = 'FETCH_PRODUCTION_REQUEST';
export const FETCH_PRODUCTION_SUCCESS = 'FETCH_PRODUCTION_SUCCESS';
export const FETCH_PRODUCTION_FAILURE = 'FETCH_PRODUCTION_FAILURE';

// Machine Report
export const FETCH_MACHINES_REQUEST = 'FETCH_MACHINES_REQUEST';
export const FETCH_MACHINES_SUCCESS = 'FETCH_MACHINES_SUCCESS';
export const FETCH_MACHINES_FAILURE = 'FETCH_MACHINES_FAILURE';

// Customer Report
export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

// Materials
export const FETCH_MATERIALS_REQUEST = 'FETCH_MATERIALS_REQUEST';
export const FETCH_MATERIALS_SUCCESS = 'FETCH_MATERIALS_SUCCESS';
export const FETCH_MATERIALS_FAILURE = 'FETCH_MATERIALS_FAILURE';

// Filter Management
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';
export const SET_PRIORITY_FILTER = 'SET_PRIORITY_FILTER';
export const SET_MACHINE_TYPE_FILTER = 'SET_MACHINE_TYPE_FILTER';
export const SET_MATERIAL_TYPE_FILTER = 'SET_MATERIAL_TYPE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

// UI State
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';

// Active Tab
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

// Refresh
export const REFRESH_REPORTS = 'REFRESH_REPORTS';
export const REFRESH_REPORT_SUCCESS = 'REFRESH_REPORT_SUCCESS';
export const REFRESH_REPORT_FAILURE = 'REFRESH_REPORT_FAILURE';

// Branch
export const SET_BRANCH = 'SET_BRANCH';
