// Create
export const CREATE_REPORT_TYPE_REQUEST = "CREATE_REPORT_TYPE_REQUEST";
export const CREATE_REPORT_TYPE_SUCCESS = "CREATE_REPORT_TYPE_SUCCESS";
export const CREATE_REPORT_TYPE_FAIL = "CREATE_REPORT_TYPE_FAIL";

// List
export const GET_REPORT_TYPES_REQUEST = "GET_REPORT_TYPES_REQUEST";
export const GET_REPORT_TYPES_SUCCESS = "GET_REPORT_TYPES_SUCCESS";
export const GET_REPORT_TYPES_FAIL = "GET_REPORT_TYPES_FAIL";

// Get by ID
export const GET_REPORT_TYPE_BY_ID_REQUEST = "GET_REPORT_TYPE_BY_ID_REQUEST";
export const GET_REPORT_TYPE_BY_ID_SUCCESS = "GET_REPORT_TYPE_BY_ID_SUCCESS";
export const GET_REPORT_TYPE_BY_ID_FAIL = "GET_REPORT_TYPE_BY_ID_FAIL";

// Get by Branch
export const GET_REPORT_TYPES_BY_BRANCH_REQUEST = "GET_REPORT_TYPES_BY_BRANCH_REQUEST";
export const GET_REPORT_TYPES_BY_BRANCH_SUCCESS = "GET_REPORT_TYPES_BY_BRANCH_SUCCESS";
export const GET_REPORT_TYPES_BY_BRANCH_FAIL = "GET_REPORT_TYPES_BY_BRANCH_FAIL";

// Get by Category
export const GET_REPORT_TYPES_BY_CATEGORY_REQUEST = "GET_REPORT_TYPES_BY_CATEGORY_REQUEST";
export const GET_REPORT_TYPES_BY_CATEGORY_SUCCESS = "GET_REPORT_TYPES_BY_CATEGORY_SUCCESS";
export const GET_REPORT_TYPES_BY_CATEGORY_FAIL = "GET_REPORT_TYPES_BY_CATEGORY_FAIL";

// Get Default
export const GET_DEFAULT_REPORT_TYPE_REQUEST = "GET_DEFAULT_REPORT_TYPE_REQUEST";
export const GET_DEFAULT_REPORT_TYPE_SUCCESS = "GET_DEFAULT_REPORT_TYPE_SUCCESS";
export const GET_DEFAULT_REPORT_TYPE_FAIL = "GET_DEFAULT_REPORT_TYPE_FAIL";

// Update
export const UPDATE_REPORT_TYPE_REQUEST = "UPDATE_REPORT_TYPE_REQUEST";
export const UPDATE_REPORT_TYPE_SUCCESS = "UPDATE_REPORT_TYPE_SUCCESS";
export const UPDATE_REPORT_TYPE_FAIL = "UPDATE_REPORT_TYPE_FAIL";

// Delete
export const DELETE_REPORT_TYPE_REQUEST = "DELETE_REPORT_TYPE_REQUEST";
export const DELETE_REPORT_TYPE_SUCCESS = "DELETE_REPORT_TYPE_SUCCESS";
export const DELETE_REPORT_TYPE_FAIL = "DELETE_REPORT_TYPE_FAIL";

// Set Default
export const SET_DEFAULT_REPORT_TYPE_REQUEST = "SET_DEFAULT_REPORT_TYPE_REQUEST";
export const SET_DEFAULT_REPORT_TYPE_SUCCESS = "SET_DEFAULT_REPORT_TYPE_SUCCESS";
export const SET_DEFAULT_REPORT_TYPE_FAIL = "SET_DEFAULT_REPORT_TYPE_FAIL";

// Generate Report
export const GENERATE_REPORT_REQUEST = "GENERATE_REPORT_REQUEST";
export const GENERATE_REPORT_SUCCESS = "GENERATE_REPORT_SUCCESS";
export const GENERATE_REPORT_FAIL = "GENERATE_REPORT_FAIL";

// Clear
export const CLEAR_REPORT_TYPE_ERRORS = "CLEAR_REPORT_TYPE_ERRORS";
export const CLEAR_REPORT_DATA = "CLEAR_REPORT_DATA";
