export const CREATE_FORMULA_REQUEST = 'CREATE_FORMULA_REQUEST';
export const CREATE_FORMULA_SUCCESS = 'CREATE_FORMULA_SUCCESS';
export const CREATE_FORMULA_FAILURE = 'CREATE_FORMULA_FAILURE';

export const GET_FORMULAS_REQUEST = 'GET_FORMULAS_REQUEST';
export const GET_FORMULAS_SUCCESS = 'GET_FORMULAS_SUCCESS';
export const GET_FORMULAS_FAILURE = 'GET_FORMULAS_FAILURE';

export const GET_FORMULA_BY_NAME_REQUEST = 'GET_FORMULA_BY_NAME_REQUEST';
export const GET_FORMULA_BY_NAME_SUCCESS = 'GET_FORMULA_BY_NAME_SUCCESS';
export const GET_FORMULA_BY_NAME_FAILURE = 'GET_FORMULA_BY_NAME_FAILURE';

export const UPDATE_FORMULA_REQUEST = 'UPDATE_FORMULA_REQUEST';
export const UPDATE_FORMULA_SUCCESS = 'UPDATE_FORMULA_SUCCESS';
export const UPDATE_FORMULA_FAILURE = 'UPDATE_FORMULA_FAILURE';

export const DELETE_FORMULA_REQUEST = 'DELETE_FORMULA_REQUEST';
export const DELETE_FORMULA_SUCCESS = 'DELETE_FORMULA_SUCCESS';
export const DELETE_FORMULA_FAILURE = 'DELETE_FORMULA_FAILURE';

export const TEST_FORMULA_REQUEST = 'TEST_FORMULA_REQUEST';
export const TEST_FORMULA_SUCCESS = 'TEST_FORMULA_SUCCESS';
export const TEST_FORMULA_FAILURE = 'TEST_FORMULA_FAILURE';
