// Formula Create
export const CREATE_FORMULA_REQUEST = "CREATE_FORMULA_REQUEST";
export const CREATE_FORMULA_SUCCESS = "CREATE_FORMULA_SUCCESS";
export const CREATE_FORMULA_FAIL = "CREATE_FORMULA_FAIL";

// Formula List
export const GET_FORMULAS_REQUEST = "GET_FORMULAS_REQUEST";
export const GET_FORMULAS_SUCCESS = "GET_FORMULAS_SUCCESS";
export const GET_FORMULAS_FAIL = "GET_FORMULAS_FAIL";

// Formula Get by Name
export const GET_FORMULA_BY_NAME_REQUEST = "GET_FORMULA_BY_NAME_REQUEST";
export const GET_FORMULA_BY_NAME_SUCCESS = "GET_FORMULA_BY_NAME_SUCCESS";
export const GET_FORMULA_BY_NAME_FAIL = "GET_FORMULA_BY_NAME_FAIL";

// Formula Update
export const UPDATE_FORMULA_REQUEST = "UPDATE_FORMULA_REQUEST";
export const UPDATE_FORMULA_SUCCESS = "UPDATE_FORMULA_SUCCESS";
export const UPDATE_FORMULA_FAIL = "UPDATE_FORMULA_FAIL";

// Formula Delete
export const DELETE_FORMULA_REQUEST = "DELETE_FORMULA_REQUEST";
export const DELETE_FORMULA_SUCCESS = "DELETE_FORMULA_SUCCESS";
export const DELETE_FORMULA_FAIL = "DELETE_FORMULA_FAIL";

// Formula Test
export const TEST_FORMULA_REQUEST = "TEST_FORMULA_REQUEST";
export const TEST_FORMULA_SUCCESS = "TEST_FORMULA_SUCCESS";
export const TEST_FORMULA_FAIL = "TEST_FORMULA_FAIL";
