// Product Spec Create
export const CREATE_PRODUCT_SPEC_REQUEST = "CREATE_PRODUCT_SPEC_REQUEST";
export const CREATE_PRODUCT_SPEC_SUCCESS = "CREATE_PRODUCT_SPEC_SUCCESS";
export const CREATE_PRODUCT_SPEC_FAIL = "CREATE_PRODUCT_SPEC_FAIL";

// Product Spec List
export const GET_PRODUCT_SPECS_REQUEST = "GET_PRODUCT_SPECS_REQUEST";
export const GET_PRODUCT_SPECS_SUCCESS = "GET_PRODUCT_SPECS_SUCCESS";
export const GET_PRODUCT_SPECS_FAIL = "GET_PRODUCT_SPECS_FAIL";

// Product Spec Get by ID
export const GET_PRODUCT_SPEC_BY_ID_REQUEST = "GET_PRODUCT_SPEC_BY_ID_REQUEST";
export const GET_PRODUCT_SPEC_BY_ID_SUCCESS = "GET_PRODUCT_SPEC_BY_ID_SUCCESS";
export const GET_PRODUCT_SPEC_BY_ID_FAIL = "GET_PRODUCT_SPEC_BY_ID_FAIL";

// Product Spec Get by Product Type
export const GET_PRODUCT_SPECS_BY_TYPE_REQUEST = "GET_PRODUCT_SPECS_BY_TYPE_REQUEST";
export const GET_PRODUCT_SPECS_BY_TYPE_SUCCESS = "GET_PRODUCT_SPECS_BY_TYPE_SUCCESS";
export const GET_PRODUCT_SPECS_BY_TYPE_FAIL = "GET_PRODUCT_SPECS_BY_TYPE_FAIL";

// Product Spec Update
export const UPDATE_PRODUCT_SPEC_REQUEST = "UPDATE_PRODUCT_SPEC_REQUEST";
export const UPDATE_PRODUCT_SPEC_SUCCESS = "UPDATE_PRODUCT_SPEC_SUCCESS";
export const UPDATE_PRODUCT_SPEC_FAIL = "UPDATE_PRODUCT_SPEC_FAIL";

// Product Spec Delete
export const DELETE_PRODUCT_SPEC_REQUEST = "DELETE_PRODUCT_SPEC_REQUEST";
export const DELETE_PRODUCT_SPEC_SUCCESS = "DELETE_PRODUCT_SPEC_SUCCESS";
export const DELETE_PRODUCT_SPEC_FAIL = "DELETE_PRODUCT_SPEC_FAIL";

// Product Spec Activate
export const ACTIVATE_PRODUCT_SPEC_REQUEST = "ACTIVATE_PRODUCT_SPEC_REQUEST";
export const ACTIVATE_PRODUCT_SPEC_SUCCESS = "ACTIVATE_PRODUCT_SPEC_SUCCESS";
export const ACTIVATE_PRODUCT_SPEC_FAIL = "ACTIVATE_PRODUCT_SPEC_FAIL";

// Product Spec Deactivate
export const DEACTIVATE_PRODUCT_SPEC_REQUEST = "DEACTIVATE_PRODUCT_SPEC_REQUEST";
export const DEACTIVATE_PRODUCT_SPEC_SUCCESS = "DEACTIVATE_PRODUCT_SPEC_SUCCESS";
export const DEACTIVATE_PRODUCT_SPEC_FAIL = "DEACTIVATE_PRODUCT_SPEC_FAIL";
