// Machine Template Create
export const CREATE_MACHINE_TEMPLATE_REQUEST = "CREATE_MACHINE_TEMPLATE_REQUEST";
export const CREATE_MACHINE_TEMPLATE_SUCCESS = "CREATE_MACHINE_TEMPLATE_SUCCESS";
export const CREATE_MACHINE_TEMPLATE_FAIL = "CREATE_MACHINE_TEMPLATE_FAIL";

// Machine Template List
export const GET_MACHINE_TEMPLATES_REQUEST = "GET_MACHINE_TEMPLATES_REQUEST";
export const GET_MACHINE_TEMPLATES_SUCCESS = "GET_MACHINE_TEMPLATES_SUCCESS";
export const GET_MACHINE_TEMPLATES_FAIL = "GET_MACHINE_TEMPLATES_FAIL";

// Machine Template Get by ID
export const GET_MACHINE_TEMPLATE_BY_ID_REQUEST = "GET_MACHINE_TEMPLATE_BY_ID_REQUEST";
export const GET_MACHINE_TEMPLATE_BY_ID_SUCCESS = "GET_MACHINE_TEMPLATE_BY_ID_SUCCESS";
export const GET_MACHINE_TEMPLATE_BY_ID_FAIL = "GET_MACHINE_TEMPLATE_BY_ID_FAIL";

// Machine Template Get by Machine
export const GET_TEMPLATES_BY_MACHINE_REQUEST = "GET_TEMPLATES_BY_MACHINE_REQUEST";
export const GET_TEMPLATES_BY_MACHINE_SUCCESS = "GET_TEMPLATES_BY_MACHINE_SUCCESS";
export const GET_TEMPLATES_BY_MACHINE_FAIL = "GET_TEMPLATES_BY_MACHINE_FAIL";

// Machine Template Update
export const UPDATE_MACHINE_TEMPLATE_REQUEST = "UPDATE_MACHINE_TEMPLATE_REQUEST";
export const UPDATE_MACHINE_TEMPLATE_SUCCESS = "UPDATE_MACHINE_TEMPLATE_SUCCESS";
export const UPDATE_MACHINE_TEMPLATE_FAIL = "UPDATE_MACHINE_TEMPLATE_FAIL";

// Machine Template Delete
export const DELETE_MACHINE_TEMPLATE_REQUEST = "DELETE_MACHINE_TEMPLATE_REQUEST";
export const DELETE_MACHINE_TEMPLATE_SUCCESS = "DELETE_MACHINE_TEMPLATE_SUCCESS";
export const DELETE_MACHINE_TEMPLATE_FAIL = "DELETE_MACHINE_TEMPLATE_FAIL";

// Machine Template Activate
export const ACTIVATE_MACHINE_TEMPLATE_REQUEST = "ACTIVATE_MACHINE_TEMPLATE_REQUEST";
export const ACTIVATE_MACHINE_TEMPLATE_SUCCESS = "ACTIVATE_MACHINE_TEMPLATE_SUCCESS";
export const ACTIVATE_MACHINE_TEMPLATE_FAIL = "ACTIVATE_MACHINE_TEMPLATE_FAIL";

// Machine Template Deactivate
export const DEACTIVATE_MACHINE_TEMPLATE_REQUEST = "DEACTIVATE_MACHINE_TEMPLATE_REQUEST";
export const DEACTIVATE_MACHINE_TEMPLATE_SUCCESS = "DEACTIVATE_MACHINE_TEMPLATE_SUCCESS";
export const DEACTIVATE_MACHINE_TEMPLATE_FAIL = "DEACTIVATE_MACHINE_TEMPLATE_FAIL";

// Machine Template Duplicate
export const DUPLICATE_MACHINE_TEMPLATE_REQUEST = "DUPLICATE_MACHINE_TEMPLATE_REQUEST";
export const DUPLICATE_MACHINE_TEMPLATE_SUCCESS = "DUPLICATE_MACHINE_TEMPLATE_SUCCESS";
export const DUPLICATE_MACHINE_TEMPLATE_FAIL = "DUPLICATE_MACHINE_TEMPLATE_FAIL";

// WebSocket Events
export const WS_MACHINE_TEMPLATE_CREATED = "WS_MACHINE_TEMPLATE_CREATED";
export const WS_MACHINE_TEMPLATE_UPDATED = "WS_MACHINE_TEMPLATE_UPDATED";
export const WS_MACHINE_TEMPLATE_DELETED = "WS_MACHINE_TEMPLATE_DELETED";
export const WS_MACHINE_TEMPLATE_ACTIVATED = "WS_MACHINE_TEMPLATE_ACTIVATED";
export const WS_MACHINE_TEMPLATE_DEACTIVATED = "WS_MACHINE_TEMPLATE_DEACTIVATED";
export const WS_MACHINE_TEMPLATE_DUPLICATED = "WS_MACHINE_TEMPLATE_DUPLICATED";

// Clear Errors
export const CLEAR_MACHINE_TEMPLATE_ERROR = "CLEAR_MACHINE_TEMPLATE_ERROR";
